PROGRAM1 = server
PROGRAM1_SRCS = ./server.c
PROGRAM1_BONUS = server_bonus
PROGRAM1_BONUS_SRCS = ./server_bonus.c

PROGRAM2 = client
PROGRAM2_SRCS = ./client.c
PROGRAM2_BONUS = client_bonus
PROGRAM2_BONUS_SRCS = ./client_bonus.c

FLAGS = -Wall -Werror -Wextra
PROGRAM1_OBJS = $(PROGRAM1_SRCS:.c=.o)
PROGRAM2_OBJS = $(PROGRAM2_SRCS:.c=.o)
PROGRAM1_BONUS_OBJS = $(PROGRAM1_BONUS_SRCS:.c=.o)
PROGRAM2_BONUS_OBJS = $(PROGRAM2_BONUS_SRCS:.c=.o)

all : $(PROGRAM1) $(PROGRAM2)

$(PROGRAM1) : $(PROGRAM1_OBJS)
	gcc $(FLAGS) $(PROGRAM1_OBJS) -o $(PROGRAM1)
$(PROGRAM2) : $(PROGRAM2_OBJS)
	gcc $(FLAGS) $(PROGRAM2_OBJS) -o $(PROGRAM2)

bonus : $(PROGRAM1_BONUS) $(PROGRAM2_BONUS)

$(PROGRAM1_BONUS) : $(PROGRAM1_BONUS_OBJS)
	gcc $(FLAGS) $(PROGRAM1_BONUS_OBJS) -o $(PROGRAM1_BONUS)
$(PROGRAM2_BONUS) : $(PROGRAM2_BONUS_OBJS)
	gcc $(FLAGS) $(PROGRAM2_BONUS_OBJS) -o $(PROGRAM2_BONUS)

clean :
	rm -rf *.o
fclean : clean
	rm -rf $(PROGRAM1) $(PROGRAM2)
	rm -rf $(PROGRAM1_BONUS) $(PROGRAM2_BONUS)
re : fclean all